name: Tests
on: push

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          bundler-cache: true
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Install deps
        run: bundle
      - name: Start server
        run: bundle exec jekyll serve --detach
      - name: Run tests
        run: bundle exec rspec
