name: Tests
on: push

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.248.0
        uses: ruby/setup-ruby@a9bfc2ecf3dd40734a9418f89a7e9d484c32b990
        with:
          bundler-cache: true
          cache-version: 1 # Increment this number if you need to re-download cached gems
      - name: Install deps
        run: bundle
      - name: Start server
        run: bundle exec jekyll serve --detach
      - name: Run tests
        run: bundle exec rspec
